"""Controladores de fluxo da UI PySide6."""

from .commit_controller import (
    clear_commit_file_selection,
    create_commit_from_selection,
    get_selected_commit_paths,
    iter_commit_items,
    on_commit_file_item_changed,
    refresh_commit_files,
    select_all_commit_files,
    update_commit_selection_label,
)
from .compare_controller import (
    clear_compare_view,
    get_compare_branches,
    on_compare_branches_changed,
    on_compare_file_selected,
    refresh_compare_branch_options,
    refresh_compare_patch,
    refresh_compare_view,
    swap_compare_branches,
)
from .history_controller import (
    clear_history_view,
    get_history_limit_value,
    load_history_commit_content,
    on_history_commit_selected,
    on_history_file_selected,
    refresh_history_patch_view,
    reload_history_commits,
)
from .import_controller import (
    apply_import_source_repo_from_combo,
    clear_import_selection,
    copy_selected_import_hashes,
    get_selected_import_summaries,
    import_selected_commits,
    load_import_source_branches,
    load_import_source_commits,
    on_import_source_branch_changed,
    on_import_source_repo_changed,
    refresh_import_source_repos,
    sync_import_target_label,
    update_import_controls_state,
    use_current_repo_as_import_source,
)

__all__ = [
    "refresh_commit_files",
    "iter_commit_items",
    "update_commit_selection_label",
    "on_commit_file_item_changed",
    "select_all_commit_files",
    "clear_commit_file_selection",
    "get_selected_commit_paths",
    "create_commit_from_selection",
    "clear_compare_view",
    "get_compare_branches",
    "refresh_compare_branch_options",
    "on_compare_branches_changed",
    "swap_compare_branches",
    "refresh_compare_view",
    "on_compare_file_selected",
    "refresh_compare_patch",
    "clear_history_view",
    "get_history_limit_value",
    "reload_history_commits",
    "on_history_commit_selected",
    "load_history_commit_content",
    "on_history_file_selected",
    "refresh_history_patch_view",
    "sync_import_target_label",
    "clear_import_selection",
    "refresh_import_source_repos",
    "on_import_source_repo_changed",
    "apply_import_source_repo_from_combo",
    "use_current_repo_as_import_source",
    "load_import_source_branches",
    "on_import_source_branch_changed",
    "load_import_source_commits",
    "get_selected_import_summaries",
    "copy_selected_import_hashes",
    "import_selected_commits",
    "update_import_controls_state",
]
